<a href="https://colab.research.google.com/github/Deepakraj22/Deepakraj22/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))
print(tf.square(2)+tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [7]:
x=tf.matmul([[1]] ,[[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [8]:
import numpy as np

In [13]:
ndarray = np.ones([3,3])
print("Tensorflow operation convert numpy array to Tensors automatically")
tensor = tf.multiply(ndarray,42)
print(tensor)

Tensorflow operation convert numpy array to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [14]:
tensor.shape

TensorShape([3, 3])

In [15]:
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])>

In [16]:
tensor.dtype

tf.float64

In [17]:
print("NumPy operation convert Tensor to numpy array automatically")
print(np.add(tensor,1))

NumPy operation convert Tensor to numpy array automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [18]:
print("The.numpy(method explicity convert a Tensor to a numpy array")
print(tensor.numpy())

The.numpy(method explicity convert a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
